services:
  react_native_app:
    build:
      context: ./native
    ports:
      - '19006:19006'
      - '19001:19001'
      - '19002:19002'
      - '8081:8081'
    working_dir: /app
    volumes:
      - ./native:/app
      - react_native_node_modules:/app/node_modules
    healthcheck:
      disable: true
    depends_on:
      - backend

  backend:
    build:
      context: ./back
    ports:
      - "8000:8000"
    working_dir: /app
    volumes:
      - ./back:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000

volumes:
  notused: